http:
  routers:
    app:
      rule: Host(`app.dev.hideoutbutler.com`)
      entryPoints:
        - web
      service: app
    api:
      rule: Host(`api.dev.hideoutbutler.com`)
      entryPoints:
        - web
      service: api
    admin:
      rule: Host(`admin.dev.hideoutbutler.com`)
      entryPoints:
        - web
      service: admin
    mockggg:
      rule: Host(`ggg.dev.hideoutbutler.com`)
      entryPoints:
        - web
      service: mockggg

  services:
    app:
      loadBalancer:
        servers:
          - url: http://frontend:5173
    api:
      loadBalancer:
        servers:
          - url: http://backend:8000
    admin:
      loadBalancer:
        servers:
          - url: http://admin:8001
    mockggg:
      loadBalancer:
        servers:
          - url: http://mock-ggg:9000
