api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  file:
    filename: /etc/traefik/dynamic.dev.yml
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json
