import { useRef, useState } from "react";
import { toPng } from "html-to-image";

import type { CharacterDetail } from "@/api/types";
import { CharacterDetailedGearView } from "@/features/characters/CharacterDetailedGearView";
import { CharacterGearDisplay } from "@/features/characters/CharacterGearDisplay";
import { CharacterStatSummary } from "@/features/characters/CharacterStatSummary";
import type { GearEstimate } from "@/features/characters/characterGearItems";
import { filterNotableCharacterGems } from "@/features/characters/characterGemFilter";
import { collectPaperDollItems } from "@/features/characters/paperDollItems";
import { formatChaos } from "@/features/items/itemMetrics";
import { PANE_SECTION_HEADING } from "@/features/items/ItemModPresentation";

export type CharacterExportLayout = "simple" | "detailed";
export type CharacterExportTheme = "transparent" | "branded" | "epic";

export interface CharacterImageExportProps {
  detail: CharacterDetail;
  league: string;
  layout: CharacterExportLayout;
  theme: CharacterExportTheme;
  gearEstimate?: GearEstimate;
}

function snapshotLabel(detail: CharacterDetail): string {
  if (detail.snapshot_fetched_at) {
    return new Date(detail.snapshot_fetched_at).toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "UTC",
      timeZoneName: "short",
    });
  }
  return new Date().toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC",
    timeZoneName: "short",
  });
}

function CharacterExportSnapshot({
  detail,
  league,
  layout,
  theme,
  gearEstimate,
}: CharacterImageExportProps) {
  const { summary } = detail;
  const notableGems = filterNotableCharacterGems(detail.gems ?? []);
  const transparent = theme === "transparent";
  const epic = theme === "epic";

  return (
    <div
      className={[
        "w-[800px] text-left text-sm text-parchment-100",
        transparent ? "bg-transparent p-2" : "rounded-md border border-ink-700 bg-ink-950 p-4 shadow-lg",
      ].join(" ")}
      data-testid={`character-export-${layout}-${theme}`}
    >
      {!transparent && (
        <header className="mb-3 border-b border-ink-700/80 pb-2">
          <h1 className="font-display text-xl font-semibold text-amber-100/95">{summary.name}</h1>
          <p className="text-sm text-parchment-200/80">
            Lv {summary.level} · {summary.class} · {league}
          </p>
          {detail.is_historical && detail.snapshot_fetched_at && (
            <p className="mt-1 text-xs text-amber-200/80">
              Historic snapshot · {snapshotLabel(detail)}
            </p>
          )}
        </header>
      )}

      {epic && gearEstimate && (
        <div className="mb-3 rounded-md border border-ember-500/30 bg-ember-950/20 px-3 py-2 text-sm">
          <span className={PANE_SECTION_HEADING}>Gear estimate </span>
          <span className="text-parchment-50">
            {gearEstimate.totalChaos > 0 ? `${formatChaos(gearEstimate.totalChaos)}c` : "—"}
            {gearEstimate.totalCount > 0 &&
              ` (${gearEstimate.pricedCount}/${gearEstimate.totalCount} items)`}
          </span>
        </div>
      )}

      {epic && detail.stat_summary && (
        <div className="mb-3">
          <CharacterStatSummary detail={detail} />
        </div>
      )}

      {layout === "simple" ? (
        <CharacterGearDisplay detail={detail} readOnly />
      ) : (
        <CharacterDetailedGearView
          equipped={collectPaperDollItems(detail)}
          jewels={detail.jewels}
          gems={notableGems}
        />
      )}

      {theme !== "transparent" && (
        <footer className="mt-4 border-t border-ink-700/80 pt-2 text-center text-[11px] text-parchment-300/70">
          <p className="font-display text-ember-200/90">Generated by Hideout Butler</p>
          <p>hideoutbutler.com · {snapshotLabel(detail)}</p>
        </footer>
      )}
    </div>
  );
}

async function copyOrDownloadPng(
  el: HTMLDivElement,
  fileName: string,
  transparent: boolean,
): Promise<"copied" | "downloaded" | "failed"> {
  try {
    const dataUrl = await toPng(el, {
      pixelRatio: 2,
      cacheBust: true,
      backgroundColor: transparent ? undefined : "#0a0a0f",
    });
    const secure = window.isSecureContext;
    if (secure && navigator.clipboard?.write) {
      try {
        const blob = await (await fetch(dataUrl)).blob();
        await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
        return "copied";
      } catch {
        // fall through to download
      }
    }
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `${fileName}.png`;
    a.click();
    return "downloaded";
  } catch {
    return "failed";
  }
}

export function CharacterImageExportActions({
  detail,
  league,
  gearEstimate,
}: {
  detail: CharacterDetail;
  league: string;
  gearEstimate?: GearEstimate;
}) {
  const [layout, setLayout] = useState<CharacterExportLayout>("simple");
  const [theme, setTheme] = useState<CharacterExportTheme>("branded");
  const [msg, setMsg] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  const runExport = async (mode: "copy" | "download") => {
    const el = ref.current;
    if (!el) return;
    setMsg("rendering…");
    const result = await copyOrDownloadPng(
      el,
      `${detail.summary.name}-${layout}-${theme}`,
      theme === "transparent",
    );
    if (result === "copied") setMsg(mode === "copy" ? "PNG copied" : "PNG copied");
    else if (result === "downloaded") setMsg("PNG downloaded");
    else setMsg("export failed");
    setTimeout(() => setMsg(null), 4000);
  };

  return (
    <div className="space-y-1 text-xs">
      <div className="flex flex-wrap gap-1">
        <select
          className="rounded border border-ink-700 bg-ink-900 px-1 py-0.5"
          value={layout}
          onChange={(e) => setLayout(e.target.value as CharacterExportLayout)}
          aria-label="Export layout"
        >
          <option value="simple">Simple</option>
          <option value="detailed">Detailed</option>
        </select>
        <select
          className="rounded border border-ink-700 bg-ink-900 px-1 py-0.5"
          value={theme}
          onChange={(e) => setTheme(e.target.value as CharacterExportTheme)}
          aria-label="Export theme"
        >
          <option value="transparent">Transparent</option>
          <option value="branded">Branded</option>
          <option value="epic">Epic</option>
        </select>
      </div>
      <div className="flex flex-wrap gap-1">
        <button type="button" className="btn-ghost px-2 py-1" onClick={() => void runExport("copy")}>
          Copy PNG
        </button>
        <button type="button" className="btn-ghost px-2 py-1" onClick={() => void runExport("download")}>
          Download PNG
        </button>
      </div>
      {msg && <p className="text-[10px] text-ui-muted">{msg}</p>}
      <div className="pointer-events-none fixed -left-[10000px] top-0" aria-hidden>
        <div ref={ref}>
          <CharacterExportSnapshot
            detail={detail}
            league={league}
            layout={layout}
            theme={theme}
            gearEstimate={gearEstimate}
          />
        </div>
      </div>
    </div>
  );
}

export { CharacterExportSnapshot };
