import { useRef, useState } from "react";
import { toPng } from "html-to-image";

import type { CharacterDetail } from "@/api/types";
import {
  CharacterDetailedGearView,
  CharacterSimpleExportBody,
} from "@/features/characters/CharacterDetailedGearView";
import { CharacterStatSummary } from "@/features/characters/CharacterStatSummary";
import type { GearEstimate } from "@/features/characters/characterGearItems";
import { formatGearEstimateLabel } from "@/features/characters/characterGearItems";
import { filterNotableCharacterGems } from "@/features/characters/characterGemFilter";
import { collectPaperDollItems } from "@/features/characters/paperDollItems";
import { dataUrlToBlob } from "@/features/items/ItemImageExport";
import type { CurrencyChaosPair } from "@/features/items/itemMetrics";
import { PANE_SECTION_HEADING } from "@/features/items/ItemModPresentation";

export type CharacterExportLayout = "simple" | "detailed";
export type CharacterExportTheme = "transparent" | "branded" | "epic";

const EXPORT_WIDTH_PX = 1280;

export interface CharacterImageExportProps {
  detail: CharacterDetail;
  league: string;
  layout: CharacterExportLayout;
  theme: CharacterExportTheme;
  gearEstimate?: GearEstimate;
  currencyChaos?: CurrencyChaosPair | null;
}

function snapshotLabel(detail: CharacterDetail): string {
  if (detail.snapshot_fetched_at) {
    return new Date(detail.snapshot_fetched_at).toLocaleString(undefined, {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
      timeZone: "UTC",
      timeZoneName: "short",
    });
  }
  return new Date().toLocaleString(undefined, {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "UTC",
    timeZoneName: "short",
  });
}

function CharacterExportSnapshot({
  detail,
  league,
  layout,
  theme,
  gearEstimate,
  currencyChaos,
}: CharacterImageExportProps) {
  const { summary } = detail;
  const notableGems = filterNotableCharacterGems(detail.gems ?? []);
  const dollItems = collectPaperDollItems(detail);
  const transparent = theme === "transparent";
  const epic = theme === "epic";

  return (
    <div
      className={[
        "box-border overflow-visible text-left text-sm text-parchment-100",
        transparent ? "bg-transparent p-2" : "rounded-md border border-ink-700 bg-ink-950 p-4 shadow-lg",
      ].join(" ")}
      style={{ width: EXPORT_WIDTH_PX, maxWidth: EXPORT_WIDTH_PX }}
      data-testid={`character-export-${layout}-${theme}`}
    >
      {!transparent && (
        <header className="mb-3 flex flex-wrap items-end justify-between gap-3 border-b border-ink-700/80 pb-2">
          <div>
            <h1 className="font-display text-xl font-semibold text-amber-100/95">{summary.name}</h1>
            <p className="text-sm text-parchment-200/80">
              Lv {summary.level} · {summary.class} · {league}
            </p>
            {detail.is_historical && detail.snapshot_fetched_at && (
              <p className="mt-1 text-xs text-amber-200/80">
                Historic snapshot · {snapshotLabel(detail)}
              </p>
            )}
          </div>
          {epic && gearEstimate && (
            <div className="rounded-md border border-ember-500/30 bg-ember-950/20 px-3 py-1.5 text-sm">
              <span className={PANE_SECTION_HEADING}>Gear estimate </span>
              <span className="text-parchment-50">
                {formatGearEstimateLabel(gearEstimate, currencyChaos ?? null)}
              </span>
            </div>
          )}
        </header>
      )}

      {epic && detail.stat_summary && (
        <div className="mb-3">
          <CharacterStatSummary detail={detail} />
        </div>
      )}

      {layout === "simple" ? (
        <CharacterSimpleExportBody
          equipped={dollItems}
          jewels={detail.jewels}
          gems={notableGems}
        />
      ) : (
        <CharacterDetailedGearView
          equipped={dollItems}
          jewels={detail.jewels}
          gems={notableGems}
          layout="grid"
        />
      )}

      {theme !== "transparent" && (
        <footer className="mt-4 border-t border-ink-700/80 pt-2 text-center text-[11px] text-parchment-300/70">
          <p className="font-display text-ember-200/90">Generated by Hideout Butler</p>
          <p>hideoutbutler.com · {snapshotLabel(detail)}</p>
        </footer>
      )}
    </div>
  );
}

async function waitForImages(root: HTMLElement): Promise<void> {
  const imgs = [...root.querySelectorAll("img")];
  await Promise.all(
    imgs.map(
      (img) =>
        new Promise<void>((resolve) => {
          if (img.complete && img.naturalWidth > 0) {
            resolve();
            return;
          }
          img.addEventListener("load", () => resolve(), { once: true });
          img.addEventListener("error", () => resolve(), { once: true });
        }),
    ),
  );
}

async function renderExportPng(
  el: HTMLDivElement,
  transparent: boolean,
): Promise<string | null> {
  try {
    await waitForImages(el);
    return await toPng(el, {
      pixelRatio: 2,
      cacheBust: true,
      backgroundColor: transparent ? undefined : "#0a0a0f",
    });
  } catch {
    return null;
  }
}

async function copyPngToClipboard(dataUrl: string): Promise<boolean> {
  if (!window.isSecureContext || !navigator.clipboard?.write) {
    return false;
  }
  try {
    const blob = dataUrlToBlob(dataUrl);
    await navigator.clipboard.write([new ClipboardItem({ "image/png": blob })]);
    return true;
  } catch {
    return false;
  }
}

function downloadPng(dataUrl: string, fileName: string): void {
  const a = document.createElement("a");
  a.href = dataUrl;
  a.download = `${fileName}.png`;
  a.click();
}

async function runCharacterPngExport(
  el: HTMLDivElement,
  fileName: string,
  transparent: boolean,
  mode: "copy" | "download",
): Promise<"copied" | "downloaded" | "failed"> {
  const dataUrl = await renderExportPng(el, transparent);
  if (!dataUrl) return "failed";

  if (mode === "download") {
    downloadPng(dataUrl, fileName);
    return "downloaded";
  }

  if (await copyPngToClipboard(dataUrl)) {
    return "copied";
  }
  downloadPng(dataUrl, fileName);
  return "downloaded";
}

export function CharacterImageExportActions({
  detail,
  league,
  gearEstimate,
  currencyChaos,
}: {
  detail: CharacterDetail;
  league: string;
  gearEstimate?: GearEstimate;
  currencyChaos?: CurrencyChaosPair | null;
}) {
  const [layout, setLayout] = useState<CharacterExportLayout>("simple");
  const [theme, setTheme] = useState<CharacterExportTheme>("branded");
  const [msg, setMsg] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  const runExport = async (mode: "copy" | "download") => {
    const el = ref.current;
    if (!el) return;
    setMsg("rendering…");
    const result = await runCharacterPngExport(
      el,
      `${detail.summary.name}-${layout}-${theme}`,
      theme === "transparent",
      mode,
    );
    if (result === "copied") setMsg("PNG copied");
    else if (result === "downloaded") setMsg("PNG downloaded");
    else setMsg("export failed");
    setTimeout(() => setMsg(null), 4000);
  };

  return (
    <div className="space-y-1 text-xs">
      <div className="flex flex-wrap gap-1">
        <select
          className="rounded border border-ink-700 bg-ink-900 px-1 py-0.5"
          value={layout}
          onChange={(e) => setLayout(e.target.value as CharacterExportLayout)}
          aria-label="Export layout"
        >
          <option value="simple">Simple</option>
          <option value="detailed">Detailed</option>
        </select>
        <select
          className="rounded border border-ink-700 bg-ink-900 px-1 py-0.5"
          value={theme}
          onChange={(e) => setTheme(e.target.value as CharacterExportTheme)}
          aria-label="Export theme"
        >
          <option value="transparent">Transparent</option>
          <option value="branded">Branded</option>
          <option value="epic">Epic</option>
        </select>
      </div>
      <div className="flex flex-wrap gap-1">
        <button type="button" className="btn-ghost px-2 py-1" onClick={() => void runExport("copy")}>
          Copy PNG
        </button>
        <button type="button" className="btn-ghost px-2 py-1" onClick={() => void runExport("download")}>
          Download PNG
        </button>
      </div>
      {msg && <p className="text-[10px] text-ui-muted">{msg}</p>}
      <div className="pointer-events-none fixed -left-[10000px] top-0 z-0" aria-hidden>
        <div ref={ref} className="inline-block overflow-visible">
          <CharacterExportSnapshot
            detail={detail}
            league={league}
            layout={layout}
            theme={theme}
            gearEstimate={gearEstimate}
            currencyChaos={currencyChaos}
          />
        </div>
      </div>
    </div>
  );
}

export { CharacterExportSnapshot };
